### ISSUE TITLE
If player injured and in VCM controlled group, it chronologically plays healing animation

### ISSUE THREAD

**Issue by TapioOfTapiola** [genesis92x/VcomAI-3.0#129]
If player is injured AND in a VCM controlled group, it chronologically plays healing animation.

**To Reproduce**
Start code from debug console:
player setdamage 0.1;
(group player) setVariable ["Vcm_Disable",true];

Every ~15 seconds the player stops and does a healing animation. The damage value does not seem to change.

Player should be excluded from such behaviour. But it may also be not desired on AI. I have seen them permanently doing this as well. If their damage value does not change, it is not only useless, but dangerous, because they are combat ineffective.

**Comment by TapioOfTapiola** [comment]
It's in the Steam addon version.

**Comment by TapioOfTapiola** [comment]
I think fn_HealSelf.sqf line 17 should be like:

if (!(isPlayer _this) && alive _this && {"FirstAidKit" in (items _this)}) then

**Comment by genesis92x** [comment]
Should be resolved now :)

**Comment by gabriele2000** [comment]
Unfortunately it's not resolved... sometimes it still do it.
